# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'DANIAL RAMZAN'
tagline:          'Portfolio Website'
description:      ''
url:              "https://danialramzan.github.io"
baseurl:          ""
github_username:  danialramzan
linkedin_username: danialramzan
google_analytics: G-03PZSBWDF0

                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Danial Zoraiz Ramzan'
  url:            https://github.com/danialramzan

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
#  - jekyll-feed #removed feed! to re-enable uncomment this line and uncomment feed like in jekyll-theme-hydeout.gemspec
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link

remote_theme: fongandrew/hydeout



#plugins:
#  - jekyll-feed





